gdrive_base_path: /mnt/gdrive  # The mount point on your VM where Google Drive is accessible

project_root_on_gdrive: RootzEngine  # The name of your main project folder on Google Drive

# Folder names relative to 'project_root_on_gdrive'
mp3_raw_folder: data/mp3_raw
mp3_enriched_folder: data/mp3_enriched
mp3_trash_folder: data/mp3_trash
output_folder: output

# Demucs settings
demucs_model: "htdemucs_ft"
# stem_pairs are implicitly handled by demucs_wrapper.py focusing on bass & drums
# If you need to configure specific stems for Demucs itself (newer versions allow --stems argument)
# you could add a list here, e.g.:
# demucs_target_stems: ["bass", "drums"]

# You can add your email here for reference if needed by any notification scripts later,
# but rclone configuration handles the Google Account for Drive access.
# contact_email: justin.anderson.sea@gmail.com
